services:
  gateway-service:
    build: ./gateway
    container_name: gateway-service-container
    ports:
      - '8080:8080'
    networks:
      - gateway_network
  auth-service:
    build: ./auth
    container_name: auth-service-container
    expose:
      - '8083'
    depends_on:
      - postgres-auth
    networks:
      - auth_network
      - gateway_network
  email-service:
    build: ./email
    container_name: email-service-container
    expose:
      - '8084'
    depends_on:
      - redis-email
    networks:
      - email_network
      - auth_network
      - email_external
  read-votes-service:
    build: ./read-votes
    container_name: read-votes-service-container
    expose:
      - '8082'
    depends_on:
      - postgres-read-votes
      - kafka-write-read-votes
    networks:
      - gateway_network
      - read_votes_network
      - kafka_write_read_votes
    environment:
      POSTGRES_USER: ${POSTGRES_READ_VOTES_USER}
      POSTGRES_DB: ${POSTGRES_READ_VOTES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_READ_VOTES_PASSWORD}
  write-votes-service:
    build: ./write-votes
    container_name: write-votes-service-container
    expose:
      - '8081'
    depends_on:
      - postgres-write-votes
      - kafka-write-read-votes
    networks:
      - gateway_network
      - write_votes_network
      - administration_network
      - kafka_write_read_votes
    environment:
      POSTGRES_USER: ${POSTGRES_WRITE_VOTES_USER}
      POSTGRES_DB: ${POSTGRES_WRITE_VOTES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_WRITE_VOTES_PASSWORD}
  kafka-write-read-votes:
    image: confluentinc/cp-kafka:7.7.7
    container_name: 'kafka-write-read-votes'
    hostname: 'kafka-write-read-votes'
    expose:
      - '9092'
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-write-read-votes:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-write-read-votes:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    networks:
      - kafka_write_read_votes
    volumes:
      - kafka_write_read_votes_data:/var/lib/kafka/data
  administration-service:
    build: ./administration
    container_name: administration-service-container
    expose:
      - '8085'
    networks:
      - administration_network
  postgres-read-votes:
    image: 'postgres:18-alpine'
    hostname: 'read_votes_db'
    container_name: read_votes_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_READ_VOTES_USER}
      POSTGRES_DB: ${POSTGRES_READ_VOTES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_READ_VOTES_PASSWORD}
    expose:
      - '5432'
    networks:
      - read_votes_network
    volumes:
      - postgres_read_votes_data:/var/lib/postgresql
  postgres-write-votes:
    image: 'postgres:18-alpine'
    hostname: 'write_votes_db'
    container_name: write_votes_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_WRITE_VOTES_USER}
      POSTGRES_DB: ${POSTGRES_WRITE_VOTES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_WRITE_VOTES_PASSWORD}
    expose:
      - '5432'
    networks:
      - write_votes_network
    volumes:
      - postgres_write_votes_data:/var/lib/postgresql
  postgres-auth:
    image: 'postgres:18-alpine'
    hostname: 'auth_db'
    container_name: auth_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
    expose:
      - '5432'
    networks:
      - auth_network
    volumes:
      - postgres_auth_data:/var/lib/postgresql
  redis-email:
    image: redis:8.4-alpine
    container_name: redis_email
    restart: unless-stopped
    expose:
      - '6379'
    networks:
      - email_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
  postgres_auth_data:
  postgres_read_votes_data:
  postgres_write_votes_data:
  kafka_write_read_votes_data:

networks:
  email_network:
    driver: bridge
    internal: true
  auth_network:
    driver: bridge
    internal: true
  gateway_network:
    driver: bridge
  email_external:
    driver: bridge
  read_votes_network:
    driver: bridge
    internal: true
  write_votes_network:
    driver: bridge
    internal: true
  administration_network:
    driver: bridge
    internal: true
  kafka_write_read_votes:
    driver: bridge
    internal: true