services:
  gateway-service:
    build: ./gateway
    container_name: gateway-service-container
    ports:
      - '8080:8080'
    networks:
      - gateway_network
  auth-service:
    build: ./auth
    container_name: auth-service-container
    expose:
      - '8083'
    depends_on:
      - postgres-auth
    networks:
      - auth_network
      - gateway_network
  email-service:
    build: ./email
    container_name: email-service-container
    expose:
      - '8084'
    depends_on:
      - redis-email
    networks:
      - email_network
      - auth_network
      - email_external
  postgres-auth:
    image: 'postgres:latest'
    hostname: 'auth_db'
    container_name: auth_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
    expose:
      - '5432'
    networks:
      - auth_network
    volumes:
      - postgres_auth_data:/var/lib/postgresql
  redis-email:
    image: redis:8.4-alpine
    container_name: redis_email
    restart: unless-stopped
    expose:
      - '6379'
    networks:
      - email_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
  postgres_auth_data:

networks:
  email_network:
    driver: bridge
    internal: true
  auth_network:
    driver: bridge
    internal: true
  gateway_network:
    driver: bridge
  email_external:
    driver: bridge