spring:
  application:
    name:
      read-votes
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  kafka:
    bootstrap-servers:
      localhost:9092
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id:
        votes
      auto-offset-reset:
        earliest
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JacksonJsonSerializer
