spring:
  application:
    name:
      auth
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/database_1
    username: admin
  config:
    import: classpath:secret.yaml

server:
  port:
    8083

jwt:
  accessTokenExpiration:
    900000
  refreshTokenExpiration:
    560000000